In [1]:
import pandas as pd

In [8]:
player = pd.read_csv("atp_players.csv")
player

C:\Users\luoxu\AppData\Local\Temp\ipykernel_6788\2189126571.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  player = pd.read_csv("atp_players.csv")

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554
...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN

In [4]:
ranking = pd.read_csv("atp_rankings_current.csv")
ranking

       ranking_date  rank  player  points
0          20240101     1  104925   11245
1          20240101     2  207989    8855
2          20240101     3  106421    7600
3          20240101     4  206173    6490
4          20240101     5  126094    4805
...             ...   ...     ...     ...
92336      20241230  2156  210732       1
92337      20241230  2159  210575       1
92338      20241230  2160  212194       1
92339      20241230  2160  135939       1
92340      20241230  2162  211389       1

[92341 rows x 4 columns]

In [9]:
player.columns

Index(['player_id', 'name_first', 'name_last', 'hand', 'dob', 'ioc', 'height',
       'wikidata_id'],
      dtype='object')

In [10]:
ranking.columns

Index(['ranking_date', 'rank', 'player', 'points'], dtype='object')